version: "3"

services:
  mongo-server:
    image: mongo
    container_name: mongo-server
    restart: always
    networks:
      - mongo-net
    ports: 
      - 27017:27017

  mongo-cli:
    image: mongo
    container_name: mongo-cli
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./:/import
    networks: 
      - mongo-net

networks: 
  mongo-net:
    driver: bridge